baseURL = "https://itsjoeoui.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "itsjoeoui | Home"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "itsjoeoui"
author = "itsjoeoui"
description = "Welcome to my website :)"
profilePicture = "https://avatars0.githubusercontent.com/u/25695219?v=4"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
displayMode = "dark"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/itsjoeoui"

[[params.socialIcons]]
icon = "fa-telegram"
title = "Telegram"
url = "https://t.me/itsjoeoui"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/itsjoeoui"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/itsjoeoui"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:idkwhoiam@itsjoeoui.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
